### ISSUE TITLE
Excerpt length

### ISSUE THREAD

**Issue by jangevaare** [TrueGristHBC/todo#1]
Our WP installation seems to be ignoring the default excerpt length of 55 words, so if we don't manually enter an excerpt we get some pretty ugly embeds of posts/pages, and entire posts will show up on the blog index.

This may be relevant:
https://codex.wordpress.org/Plugin_API/Filter_Reference/excerpt_length

**Comment by r3dunlop** [comment]
Excerpt defaulted to 55 words. Can get fancier later if needed.
