### ISSUE TITLE
API for usernames of Full Members

### ISSUE THREAD

**Issue by jangevaare** [TrueGristHBC/todo#14]
I just broke all the bulk buy spreadsheets again by making a temporary menu change on the website, so I am reminded that we could really use a more stable solution for this than scraping lists with google sheets

**Comment by jangevaare** [comment]
Now using tables instead of lists, which is adequately stable for our purposes

**Comment by r3dunlop** [comment]
Added function to allow querying of users through REST API. Needs a group endpoint added. Once this is done, retrieving full members should be 'unbreakable'.

**Comment by r3dunlop** [comment]
API returns whether someone is a full member. Just need an http request script for google sheets now. Working on this.

**Comment by r3dunlop** [comment]
This script works to read if someone is a current full member or not from rest API. Include as a script in google sheets:
```
function IsFullMember(username) {
    var url = 'https://truegrist.ca/wp-json/wp/v2/users/?slug='
    + username
    var response = UrlFetchApp.fetch(url, {'muteHttpExceptions': true});
    var json = response.getContentText();
    var data = JSON.parse(json);
    Logger.log(data);
    return data[0]['full_member']
}
```
Afterwards call `=IsFullMember(cell_with_username)` to get a bool of whether they are a full member or not.

I'm not sure if we will have to program a trigger, or if this will get reloaded upon page reload by a user. I'm thinking the later. **We no longer need to worry about matching weird list and table formats in an XML scrape**
