### ISSUE TITLE
Embed of MoA, CoC, etc from github

### ISSUE THREAD

**Issue by jangevaare** [TrueGristHBC/todo#5]
I would like to transition to having the text of our Memorandum of Association and other important, periodically updated documents refer to the version controlled documents on our github. I'm unsure if the fact that markdown is being used right now will cause difficulty - if so we can move to using html for the github hosted documents.

e.g.
https://truegrist.ca/memorandum/
vs.
https://github.com/TrueGristHBC/Memorandum-of-Association

**Comment by jangevaare** [comment]
This plugin may be useful: https://wordpress.org/plugins/remote-content-shortcode/

**Comment by jangevaare** [comment]
remote html content was indeed the easiest - https://truegrist.ca/memorandum/ now loads github.com/TrueGristHBC/docs/memorandum_of_association.html

**Comment by r3dunlop** [comment]
Github also has an API for things like gists. It might not look great though.

**Comment by jangevaare** [comment]
Organizations can't have gists AFAIK, hence the repo. 

The remote content for the pledge is done now as well so I will close.
